config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  root "cards#index"
  resources :cards, only: %i[index show]
  resources :supertypes, only: %i[index show]
  resources :types, only: %i[index show]
  resources :subtypes, only: %i[index show]
  resources :cardsets, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :supertype
  belongs_to :cardset

  has_many :card_types
  has_many :types, through: :card_types

  has_many :card_subtypes
  has_many :subtypes, through: :card_subtypes

  validates :name, :artist, :imageurl, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["card_subtypes", "card_types", "cardset", "subtypes", "supertypes", "types"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["artist", "hp", "name", "text"]
  end
end

app/models/card_subtype.rb
class CardSubtype < ApplicationRecord
  belongs_to :card
  belongs_to :subtype
end

app/models/card_type.rb
class CardType < ApplicationRecord
  belongs_to :card
  belongs_to :type
end

app/models/cardset.rb
class Cardset < ApplicationRecord
  has_many :locations
  has_many :cards

  validates :name, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :cardset
  validates :latitude, :longitude, presence: true
end

app/models/subtype.rb
class Subtype < ApplicationRecord
  has_many :card_subtypes
  has_many :cards, through: :card_subtypes

  validates :name, presence: true, uniqueness: true
end

app/models/supertype.rb
class Supertype < ApplicationRecord
  has_many :cards
  validates :name, presence: true, uniqueness: true
end

app/models/type.rb
class Type < ApplicationRecord
  # belongs_to :card_types
  has_many :card_types
  has_many :cards, through: :card_types

  validates :name, presence: true, uniqueness: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.includes(:cardset, :supertype, :types, :subtypes)

    if params[:search].present?
      @cards = @cards.where("name LIKE ? OR artist LIKE ? OR text LIKE ?", "%#{params[:search]}%",
                            "%#{params[:search]}%", "%#{params[:search]}%")
    end

    if params[:set].present? && params[:set] != "All Sets"
      @cards = @cards.where(cardset_id: params[:set])
    end

    @cards = @cards.order(:name).page(params[:page])
  end

  def show
    @card = Card.find(params[:id])
    # associated tables
    @supertype = @card.supertype
    @types = @card.types
    @cardset = @card.cardset
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper

end

app/helpers/cardsets_helper.rb
module CardsetsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subtypes_helper.rb
module SubtypesHelper
end

app/helpers/supertypes_helper.rb
module SupertypesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/common/_form.erb
<%= search_form_for(@q, url: cards_path, method: :get, class: 'level') do |f| %>
  <%= f.search_field :name_or_artist_or_text_i_cont_any as 'search', placeholder: "Search", class: 'level-item' %>
  <%= f.submit name: "search", class: 'level-item' %>
<% end %>

app/views/common/_menu.html.erb
<header class="has-shadow">
  <nav class="navbar is-spaced" role="navigation" aria-label="main navigation">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to 'Home', root_path%>
      </div>
      <div class="navbar-item">
        <%= link_to 'Sets', cardsets_path%>
      </div>
      <div class="navbar-item">
        <%= link_to 'SuperTypes', supertypes_path%>
      </div>
      <div class="navbar-item">
        <%= link_to 'Types', types_path%>
      </div>
        <div class="navbar-item">
        <%= link_to 'Subtypes', subtypes_path%>
      </div>
      <div class="navbar-item">
        <%= link_to 'About', pages_about_path%>
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="level">
          <!-- search form -->
          <%= render 'cards/form' %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/about.html.erb
<h1>About</h1>

<h2>Datasets</h2>
<p>I’ll be using the pokemon card data set and faker for location data.
The card table contains information such as name of the card, the number of hit points, the artist, description text, a URL to the card image.</p>
<p>A pokemon card can be categorized based on the card set that it was released in and its supertype.</p>
<p>A pokemon card can be labeled with different types and subtypes.</p>
<p>A card set has information on its name, series, and release date.</p>
<p>The faker location data is used to generate locations that the set is available to purchase.</p>

<h2>ERD Database Diagram</h2>
<img src= <%= image_tag "ERD Diagram.png" %> alt="Pokemon Card ERD Database Diagram">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PokemonCards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: 'common/menu'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="content container mt-6">
  <div class="columns">
    <div class="column">
      <h1>Datasets</h1>
      <p>We will be using the
        <%= link_to "pokemon card", "https://docs.pokemontcg.io/", :target => "_blank" %>
        data set.</p>
      <h2>Card Table</h2>
      <p>The card table contains information such as:</p>
      <ul>
        <li>the name of the card</li>
        <li>the number of hit points</li>
        <li>the artist</li>
        <li>the description text</li>
        <li>a URL to the card image</li>
      </ul>
      <h2>Categorization</h2>
      <p>A pokemon card can be categorized based on the card set that it was released in, its supertype, type, and subtype.</p>
      <h2>Associations</h2>
      <p>A pokemon card can be of different types and subtypes.</p>
      <p>A pokemon card can be only one supertype and is released in one set.</p>
      <p>A card set has information on its name, series, and release date.</p>
      <%# <p>The faker location data is used to generate locations that the set is available to purchase.</p> %>
    </div>
    <div class="column">
      <h2>ERD Database Diagram</h2>
      <%= image_tag "ERD Diagram.png", alt: "ERD Diagram" %>
    </div>
  </div>
</div>
<div class="section">
</div>